baseURL = "#"
languageCode = "en-us"
theme = "vipin"

[params]
    title = "Vipin Valiyattoor"
    author = "Vipin Valiyattoor"
    description = "Website title"
   # copyright = "Vipin"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Dr. Vipin Valiyattoor"
		tagline = "Assistant Professor"
		location = "Department of Economic Sciences, IISER Bhopal"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/vipin-valiyattoor-410b72aa/"
            title = "LinkedIn"		
       # [[params.social.list]]
          #  class = "fab"
           # icon = "fa-stack-overflow"
          #  url = "https://stackoverflow.com/users/14690729/vipin-valiyattoor?tab=profile"
          #  title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/vipinvaliyattoor"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/vipinvaliyattoo"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "https://scholar.google.com/citations?user=ZVL-P94AAAAJ&hl=en"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "ai-researchgate"
            url = "https://www.researchgate.net/profile/Vipin_Valiyattoor"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
        [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "experience"
    
    [[params.showInAccordion]]
        item = "publication"
    #[[params.showInAccordion]]
       # item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = " I am a Ph.D. graduate in Economics from the Indian Institute of Technology Madras and presently working as an Assistant Professor at the Department of Economic Sciences, IISER Bhopal. My areas of specialization are Microeconomics, Applied Econometrics, Industrial Economics and Efficiency and Productivity Analysis. My research interests lie in applied economic analysis,  particularly the performance evaluation using Data Envlopment Analysis(DEA) and Bootstrap DEA approach. I am also interested in studies using primary survey data."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Assistant Professor"
            dates = "2020 - *Present*"
            company = "Department of Economic Sciences, Indian Institute of Science Education and Research Bhopal."
            #details = "#"
        [[params.experience.list]]
            position = "Guest Faculty"
            dates = "2020"
            #link = "#"
            company = "Department of Humanities and Social Sciences, Indian Institute of Technology Madras."
      [[params.experience.list]]
            position = "Research Consultant"
            dates = "2019-2020"
            details = "Worked as Research Consultant of Tamil Nadu Household Panel Survey at MIDS Chennai (A project in partnership with Department of Economics and Statistics, Government of Tamil Nadu and Survey Research Centre, University of Michigan, U.S)." 
            #link = "#"
            company = "Madras Institute of Development Studies, Chennai."
        [[params.experience.list]]
            position = "Guest Faculty"
            dates = "2013-14"
            #link = "#"
            company = "Government Arts and Science College, Kozhikkode."
    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Economics"
            college = "Indian Institute of Technology Madras"
            dates = "2014 - 2019"
            thesis_title = "Performance of Indian Industries: Conventional and Bootstrap-Based Inferences (Supervisor: Dr Anup Kumar Bhandari)."
            thesis_link = "https://drive.google.com/file/d/1c_5kWFRs4S7L7Bpkn3abIZjE_Ar4ZYtc/view?usp=sharing"
        [[params.education.list]]
            degree = "B.Ed. in Social Sciences"
            college = "Farook Training College Kozhikkode, affiliated to  University of Calicut, Kerala."
            dates = "2013"
            #thesis_title = "Effect of humans on other humans: a study of human behavior."
            #thesis_link = "#"
             [[params.education.list]]
            degree = "M.A. in Economics"
            college = "Farook College (Autonomous) Kozhikkode, affiliated to  University of Calicut, Kerala."
            dates = "2010 - 2012"
            #thesis_title = "Effect of humans on other humans: a study of human behavior."
            #thesis_link = "#"
       
        [[params.education.list]]
            degree = "B.A. in Economics"
            college = "Pocker Sahib Memorial Orphanage (PSMO) College, Tirurangadi, Malappuram, affiliated to University of Calicut, Kerala."
            dates = "2007 - 2010"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Outsourcing and Firm Performance Nexus: An Analysis using the Conventional and Panel Double-bootstrap Procedure."
            authors = "Vipin Valiyattoor and Anup Kumar Bhandari"
            date = "2020"
            journal = "Research in International Business and Finance (2020)."
            link = "https://doi.org/10.1016/j.ribaf.2020.101279"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Conventional Procedure vis-`a-vis Bootstrap-Based Corrections of Efficiency Analyses."
            authors = "Vipin Valiyattoor and Anup Kumar Bhandari"
            date = "2020"
            journal = "Indian Growth and Development Review"
            link = "https://doi.org/10.1108/IGDR-04-2019-0035"
            type = "Journal Articles"
		
[[params.publication.list]]
            title = "Efficiency and Related Technological aspects of Food Processing Industry in India: A Non-Parametric Analysis."
            authors = "Anup Kumar Bhandari and Vipin Valiyattoor"
            date = "2016"
            journal = "Journal of Developing Areas "
            link = " https://muse.jhu.edu/article/626804"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Does Export Intensity Affect Firm Performance? Evidence from Basic Metal Industry in India."
            authors = "Vipin Valiyattoor and Anup Kumar Bhandari"
            date = "2016"
            journal = "Conference Proceedings of XI Annual International Conference of Forum for Global Knowledge Sharing"
            link = "http://fgks.in/images/pdf/conf/2016/Vipin.pdf"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Data Envelopment Analysis"
            skillrating = 95
        [[params.skill.list]]
            skill = "STATA"
            skillrating = 93
        [[params.skill.list]]
            skill = "MATLAB"
            skillrating = 85
        [[params.skill.list]]
            skill = "Eviews"
            skillrating = 60
        [[params.skill.list]]
            skill = "R"
            skillrating = 80
        [[params.skill.list]]
            skill = "DEAP and Frontier"
            skillrating = 98
         [[params.skill.list]]
            skill = "LaTeX and MS Office."
            skillrating = 97

            


    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Cycling"
        [[params.hobby.list]]		
		    hobby = "Meditation/Yoga"
