name = "vipin"
license = "MIT"
licenselink = "https://vipinvaliyattoor.github.io/"
description = "Portfolio and blog theme with multiple theme colors"
homepage = "https://vipinvaliyattoor.github.io/"
tags = ["portfolio", "accordion", "resume", "blog"]
features = ["responsive", "dark", "clean"]
min_version = "0.55"

[author]
  name = "Vipin Valiyattoor"
  homepage = "https://vipinvaliyattoor.github.io/"
